preserve reading order
slub/textract2page pull request #6
Opened 2023-05-15 14:23 UTC by rue-a

2023-05-16 08:56 UTC, rue-a commented
test fails bcs the target tree is not updated (does not contain readingOrder)

2023-05-16 15:16 UTC, bertsky requested changes
I recommend adding a CLI option which controls this behaviour (e.g. a flag `--line-regions` or a choice option `--dummy-region=[line,page]`).

2023-05-16 15:16 UTC, bertsky commented on textract2page/convert_aws.py
> +        pagexml_text_region.add_TextRegion(pagexml_text_region_line)
It's of course possible in PAGE-XML to use recursive regions, but not all tools (including not all OCR-D processors) actually iterate below the top level. So at this point I'd rather add the line-regions directly to the page.

2023-05-17 07:07 UTC, rue-a commented
> I recommend adding a CLI option which controls this behaviour (e.g. a flag `--line-regions` or a choice option `--dummy-region=[line,page]`).

Maybe we should rather add the TextRegions for each line in any case and give an option `--preserve-textract-reading-order`, which defaults to `True`. If recursive regions are not a thing, I don't see the point in a page-encompassing region.

2023-05-17 10:05 UTC, bertsky commented
Yes, maybe so. Recursive regions are obligatory in the presence of tables, though. When we start supporting these, we will get two additional structural levels from Textract (TABLE and CELL), corresponding to TableRegion and (recursive) TextRegion. So there will not be a need for artificial text regions inside tables. Similar for forms.

So agreed – let's just drop the page-encompassing region unconditionally.

2023-05-22 13:38 UTC, merged